### ISSUE TITLE
ViP behavior is strange

### ISSUE THREAD

**Issue by nicoe** [tweekmonster/braceless.vim#15]
While viP do what is expected, when using ViP (which I happen to do a lot because the text-objects are linewise objects and my mind uses V in that case) the line selected are the one from the next indent level. This is a really strange behaviour that I think is worth some documentation (or maybe even a workaround).

**Comment by tweekmonster** [comment]
`viP` and `ViP` are supposed to do the same thing.  This is a regression and I need to add test cases for it.  Thanks for reporting!

**Comment by tweekmonster** [comment]
The script that's related to this issue needs to be refactored.  It was part of the early stages of development when selection was taken into account when scanning for a single block.  This is going to end up being related to #1 which I'm going to try to work on more this weekend.
