### ISSUE TITLE
Indent mode gets confused by brackets in docstrings.

### ISSUE THREAD

**Issue by OptiverTimAll** [tweekmonster/braceless.vim#18]
Consider the following function:

```
def print_bracket():
    """
    Prints a bracket.

    Here's an example:

        >>> print_bracket()
        (

    """
    print "("
```

Everywhere after the unmatched bracket in the docstring, Braceless' indent mode gets confused about what the new indent level should be. If you delete that line, it's fine. Notet hat Braceless is not confused by the unmatch bracket in the `print` statement, just the one in the docstring.

**Comment by tweekmonster** [comment]
Thanks for catching this!  Should be fixed now.
