### ISSUE TITLE
Disable PEP8 style indenting?

### ISSUE THREAD

**Issue by jperras** [tweekmonster/braceless.vim#24]
Is there a way of disabling the PEP8-style of indenting arguments when they are split across multiple lines?

In case I'm not completely clear: the indentation style whereby the callable arguments are aligned under the opening parenthesis when the arguments are split across multiple lines like so:

``` python
x =  my_function(one, two, three,
                 four, five)
```

is what I'd like to avoid, due to our internal company coding style guidelines. I attempted to locate a setting of sorts within the vimscript of Braceless, but came up short.

Thanks for the great plugin!

**Comment by tweekmonster** [comment]
Thanks :smile:

If you leave off `+indent` in the `BracelessEnable` command, it will let the builtin Python indent handler take over.  Unfortunately, that also disables the contextual indentation for blocks.

May I ask what your company's guidelines are regarding indentation?  Depending on how not-weird it is, I could probably make it customizable for compliance.  I'm in the middle of adding auto-formatting that will wrap block lines as you type, so your input could be significant for this.

**Comment by jperras** [comment]
@tweekmonster right, the contextual indentation for blocks is something I'd like to keep.

So, the indentation rules are _almost_ identical to the [PEP8 indentation rules](http://pep8.org/#indentation), except the following:

``` python
foo = long_function_name(var_one, var_two,
                         var_three, var_four)
```

The problem that occurs with something like that is that it's very easy to end up jutting against the righthand 80/100 cols margin. Instead, we expect the following:

``` python
foo = long_function_name(var_one, var_two,
    var_three, var_four)
```

which is somewhat hilariously explicitly disallowed in the PEP8 styleguide I linked. This example is _also_ more in line with how you would perform the same operation for conditional `if` statements, e.g.:

``` python
# No extra indentation.
if (this_is_one_thing and
    that_is_another_thing):
    do_something()
```

of course, this example is somewhat coincidental with the fact that `if (` is exactly 4 characters long, meaning that the continuation line is perfectly aligned at all times. I guess we simply prefer the visual symmetry in having our overly-long conditional statements indented in the same visual manner as our overly long arguments to callables.

… the more I explain this, the more I realize that providing the hooks to make something like this customizable must be a complete pain in the butt. If you'd rather not go down that road, I'd completely understand!

**Comment by tweekmonster** [comment]
@jperras Nah, company coding standards are what they are for a reason regardless of how silly they seem.  I don't have a mission statement for this plugin, but my overall goal is to enhance and not break the workflow.  So, I'll leave this issue open until I find some time to add finer control over the indentation rules.

I know this plugin can be a little confusing, but if you just want to hack it to get it working in the meantime, take a look at this function: https://github.com/tweekmonster/braceless.vim/blob/master/autoload/braceless/python.vim#L31

The first two `if` statements deal with `if` and `def` blocks, respectively.  The third deals with function calls (solid text followed by parenthesis).  What you can do is take the return values and adjust them.  As long as that function returns a value greater than -1, Braceless's fallback indent won't take over.  `a:col_head[0]` is the line the open parenthesis is on, and `a:col_head[1]` will be the position where the open parenthesis starts.

**Comment by tweekmonster** [comment]
@jperras I pushed a branch that gives some options to override the indentation you mentioned.  Would you mind trying it out and giving some feedback on it?

**Comment by jperras** [comment]
@tweekmonster will do! Thanks for the docs on it; my vimscript is lackluster. I'll report back shortly.

**Comment by tweekmonster** [comment]
@jperras I hope you were able to have happy good time fun with the custom settings.  Is this good to go?  

I was also wondering if you've come across any coding guidelines that treat lists, tuples, and dicts differently from what PEP8 suggests.

**Comment by jperras** [comment]
@tweekmonster pardon the delay!

So, I switched to the `indent-configure` branch and attempted to set the specified configurations:

```
let g:braceless_cont_call = 1
```

but it didn't seem as though anything changed. I then tried to change the indent level to `2` and `0` and `-1` both in execute mode and within the configuration file, but I didn't notice a change in behaviour.

What am I messing up?

**Comment by tweekmonster** [comment]
`g:braceless_cont_call` is for functions calls, e.g. `x = somefunc()` since they're regarded differently in PEP8 from block statements.  Did you set `g:braceless_cont_block` to 1 as well?  That's for things like `def somefunc(args):` or `if (grouping):`

**Comment by jperras** [comment]
I set both of those to `1`. No errors on startup, and I verified that the variables are loaded in the current session by checking their value in execution mode, but still no dice – it still indented to the opening paren:

![crappy image](http://snaps.nerderati.com/STyCf.png)

Sorry for all the trouble – I must be doing something wrong!

**Comment by tweekmonster** [comment]
@jperras Thanks.  It looks like I missed a part of the solution.  Break the line at the opening parenthesis and it should drop to the correct level.  I'll look into this.

Are block indents correct?

**Comment by tweekmonster** [comment]
I just updated the branch.  It should correct that indent example you gave.

> Sorry for all the trouble – I must be doing something wrong!

Also enough of that!  VimL is pretty confusing and sometimes terrible, and I'm mixing it with imaginary Python block boundaries.  Mistakes will be made and people will get hurt from time to time.  No big deal.

**Comment by jperras** [comment]
@tweekmonster that did it – thanks! A big :+1: from me.

**Comment by tweekmonster** [comment]
@jperras Cool.  Will be merging into master in a few minutes. :tada:
