### ISSUE TITLE
Easyoperator feature request

### ISSUE THREAD

**Issue by jonathf** [tweekmonster/braceless.vim#25]
Awesome plugin you have here.

As noted in the helpfile, easymotion is awesome and the fact that braceless works well with it makes it a very good fit for me.

I have a feature request that expands on the same idea. (Or description help if already implemented.) Is it possible to extend braceless to also support easy-operator-{phrase,line}:
https://github.com/haya14busa/vim-easyoperator-phrase
https://github.com/haya14busa/vim-easyoperator-line

**Comment by tweekmonster** [comment]
Thanks :smile:  I don't use either of those, but vim-easyoperator-line looks like it could be useful.  I'll look into that.

I'm not seeing the potential with vim-easyoperator-phrase, though.  Could you give me an example of how it would be useful specifically for Python dev?

**Comment by jonathf** [comment]
I apologies. It seems I'm a bit out of date with my comment.

I while back when I first installed easy-motion, it didn't properly support operator dependent movement. You had to install one of the operator modules for this.

It seems though, that this is no longer an issue. everything worked out of the box. Also without installing any of the operator modules.

Anyways, keep up the good work.
