### ISSUE TITLE
Once selected a text object, expand the selection?

### ISSUE THREAD

**Issue by for-coursera** [tweekmonster/braceless.vim#3]
Let's say I have a code block like this:

```
1.    def decr(d, a):
2.       r = {}
3.        for key, value in d.items():
4.           if key == a:
5.               value -= 1 #### my cursor is here
6.          r[key] = value
7.        return r
```

…and my cursor is on `value -= 1` line. Once I press `vaP`, I get the `if` structure selected. But is it possible then to expand the selection somehow? Or, is it possible to pass some numeric argument before the selecting may be?

**Comment by tweekmonster** [comment]
We're talking about this in #1.  I already have code that I'm going to push soon for adding counts to block operations, but I want to fix TravisCI first so I can get some tests in for this.

**Comment by tweekmonster** [comment]
Now you can use `v2aP`

**Comment by for-coursera** [comment]
> Now you can use v2aP

Thanks! Works like a charm. And any thoughts on selection's expansion may be? :) Or do we close this issue?

**Comment by tweekmonster** [comment]
What do you mean by expansion?  There's a discussion about block motions in #1.

**Comment by for-coursera** [comment]
> What do you mean by expansion? 

Something like [that](https://github.com/terryma/vim-expand-region) probably -- but for indented structures.

E.g., as for the code shown above, if my cursor is at line 5, and I press `vaP`, the `if` block gets selected, right? But what if add an additional shortcut, pressing which after the selection would expand this particular selection further? Press it once – and the `for` block gets selected; press it twice – and then the whole function is selected?

**Comment by tweekmonster** [comment]
Hmm, I think this is already covered if you press `vaPaPaP`.  It's not exactly streamlined, but gets the job done.  And a quick glance at their readme looks like you could define `aP` in its region config.

**Comment by for-coursera** [comment]
> I think this is already covered if you press vaPaPaP

Oh, thanks for pointing :). Somehow I was too slow just to think of it :).
