### ISSUE TITLE
E132: Function call depth is higher than 'maxfuncdepth'

### ISSUE THREAD

**Issue by ghost** [tweekmonster/braceless.vim#30]
I use macvim and vim-coffee-script, when I open a coffee file, it show 
"Error detected while processing function braceless#highlight#update[7]..braceless#scan_head[69].."

**Comment by ghost** [comment]
highlight does't work in coffee, Does the plugin Compatible with vim-coffee-script?

**Comment by tweekmonster** [comment]
Do you have an example script that caused that error?  I can't reproduce it.

> highlight does't work in coffee, Does the plugin Compatible with vim-coffee-script?

I'm using [kchmck/vim-coffee-script](https://github.com/kchmck/vim-coffee-script) and it works for me.  I'm using `BracelessEnable +indent +highlight-cc2`.

**Comment by ghost** [comment]
I'm using `BracelessEnable +indent +fold +highlight`,  this is my config file [vimrc](https://github.com/manielng/Macvim/blob/master/.vimrc.local#L155)

**Comment by tweekmonster** [comment]
Do you have example coffeescript code that causes the error?

**Comment by ghost** [comment]
I'm using youcompleteme and ultisnips, when I input fun and then press tab key the error happend,
![screen shot 2016-07-17 at 10 55 36](https://cloud.githubusercontent.com/assets/18302598/16898603/084fe11c-4c12-11e6-94e9-fc6a1f599b99.jpg)

**Comment by tweekmonster** [comment]
Thanks I was able to reproduce it.  I'll look into it.
