### ISSUE TITLE
Custum popup handling for <cr> mapping

### ISSUE THREAD

**Issue by eth3lbert** [tweekmonster/braceless.vim#32]
Hi @tweekmonster,  thanks for the great plugin.

I was wondering if you could supply a method to handling popup menu in `<cr>` mapping.
Something like the following code at the beginning of `function braceless#python#override_cr(...)`.

```
if pumvisible() && get(g:, 'braceless_pum_handling', "") != ""
    let Fn = function(g:braceless_pum_handling)
    return Fn()
  endif
```

So we could use `let g:braceless_pum_handling = "g:Custom_Fn"` to make things work.

Or could you adding a variable to not mapping the `override_cr`, like following in `function! braceless#python#init()`

```
  if get(g:, 'braceless_python_override_cr', 0)
    silent! inoremap <expr><unique><silent><buffer> <cr> braceless#python#override_cr()
  endif
```

So we could use custom `<cr>` mapping like `inoremap <silent> <expr><buffer><cr> pumvisible()? g:Custom_Fn() : braceless#python#override_ce()` without losing any benefit from braceless.

Thanks for the great plugin again.

**Comment by eth3lbert** [comment]
Oh my bad, we could overwrite the mapping by filetype autocmd so something like 

```
autocmd MyAutoCmd FileType python inoremap <silent> <buffer><cr> <C-r>=MyBracelessDeopleteCr()<cr>
```

actually works.

**Comment by blueyed** [comment]
How does your MyBracelessDeopleteCr look like? (just out of curiosity)

**Comment by eth3lbert** [comment]
Here you are

``` viml
  function! ExpandOrComplete() abort
    if exists('g:deoplete#_context')
      let menu = get(v:completed_item, 'menu', 'None')
      return menu =~ '[US]'? UltiSnips#ExpandSnippet() : deoplete#close_popup()
    else
      return "\<C-y>"
    endif
  endfunction
  function! MyBracelessDeopleteCr() abort
    return pumvisible()? ExpandOrComplete() : braceless#python#override_cr()
  endfunction
```
