### ISSUE TITLE
g] doesn't work?

### ISSUE THREAD

**Issue by goodboy** [tweekmonster/braceless.vim#37]
The binding of [`g]`](http://vimdoc.sourceforge.net/htmldoc/tagsrch.html#g]) to `:tselect` doesn't seem to work after installing this plugin?

Is this expected?
I'd love to have both since I use tags quite often.

**Comment by goodboy** [comment]
Ahh I found where you document this:
```vimL
By default, these let you move around using the [[ and ]] keys.  The following
sequences are also mapped with these keys:                                    
                                                                              
  g]    Move forward to an increased indent level                             
  g[    Move backward to a decreased indent level                             
                                                                              
Default:                                                                      
                                                                              
  let g:braceless_jump_prev_key = '['                                         
  let g:braceless_jump_next_key = ']'                                         
```

So my question now is how do you disable these additional mappings?

**Comment by tweekmonster** [comment]
Set them to empty strings.  In hindsight, these should've been disabled by default.

**Comment by tweekmonster** [comment]
Actually you're talking about just disabling `g[` and `g]`.  Setting those variables to empty strings will also disable `[[` and `]]`.  But, with the other issue you brought up in #38, you probably still want to do that.

**Comment by goodboy** [comment]
@tweekmonster ok so then how do I access the `jump_x_key` behavior whilst also avoiding the conflict with `g]`?

~Maybe there's a better default mapping for what `[[` and `]]` (`]k` for key?) is currently doing and~ maybe it's better to just avoid duplicate mappings for the same behavior (i.e. rip out `g[` and `g]`)?

**Comment by goodboy** [comment]
@tweekmonster I removed the duplicate mappings for `g` and now everything works as expected.

If I also remove it from the docs will you take a PR?
