### ISSUE TITLE
Losing backslash and double quotes when joining two lines together

### ISSUE THREAD

**Issue by peaceant** [tweekmonster/braceless.vim#40]
Example joining (`J`) two lines together:
```
["Foo \"bar\"", 
"foobar"]
```
Result:
```
["Foo \"bar , "foobar"]
```

If I set in my vimrc this:
```
let g:braceless_format = {
	\ 'clean_collections': 0,
	\ 'clean_commas': 0,
	\ 'clean_slices': 0,
	\ 'clean_dot': 0,
	\ 'join_string': 0,
	\ 'clean_whitespace': 0,
	\ 'clean_string': 0
\ }
```

then the result is this:
```
["Foo \"bar ", "foobar"]
```

Still missing backslash... :-(

**Comment by tweekmonster** [comment]
It looks like you might not have syntax highlighting enabled.  Is that the case?  It's required for detecting and ignoring strings/comments.

**Comment by peaceant** [comment]
No I have syntax highlighting turned on. I've stripped down my init.vim file to this:

```
" NVIM 0.1.7.
syntax on

call plug#begin('~/.config/nvim/plugged')
Plug 'tweekmonster/braceless.vim'
call plug#end()

autocmd FileType python BracelessEnable +indent
```

I'm still losing backslash and double quote when joining (with `J` key) lines with escaped double quotes.

**Comment by tweekmonster** [comment]
Okay, it is a syntax issue.  I guess `pythonEscape` was added to the syntax and it highlights `\"` differently.

I'm using a plugin for syntax highlighting, which is why I couldn't reproduce it: https://github.com/hdima/python-syntax
