### ISSUE TITLE
zf is unconditionally mapped to a notification

### ISSUE THREAD

**Issue by hardenedapple** [tweekmonster/braceless.vim#44]
Hi there,

I have a mapping for `zf` that doesn't change the fold state.
`braceless#fold#enable_fast()` unconditionally sets `zf` to call `no_manual_msg()`.

Could you add a conditional to that action please?

If you could figure out a way to check the `maparg()` of that key sequence I guess automatically would be best, but that seems like it would be flaky, and I'd be happy with a global variable like `g:braceless_nomap_zf` or the like.

Thanks.

**Comment by tweekmonster** [comment]
What do you have `zf` set to?  Is it fold related at all?

**Comment by tweekmonster** [comment]
Also, very sorry for the late reply!

**Comment by hardenedapple** [comment]
no problem! It's not a real pain point for me.

I have `zf` mapped to enter a [submode](https://github.com/kana/vim-submode) so that `j` does the equivalent of `zj`, `k` does the equivalent of `zk` and a bunch things along the lines of easily opening/closing/navigating around folds.

It doesn't create/destroy folds though.

The actual map is `<Plug>(submode-before-entering:folds:with:zf)<Plug>(submode-before-entering:folds)<Plug>(submode-enter:folds)` which is automatically generated by that plugin.

**Comment by tweekmonster** [comment]
I updated it to ignore existing maps.  Hope that works!
