### ISSUE TITLE
No highlight in gvim, fine in vim though

### ISSUE THREAD

**Issue by AlbericC** [tweekmonster/braceless.vim#5]
with the same `.vimrc`, and no `.gvimrc`, I can't get te indent guide to appear. It works perfectly in vim, though.

**Comment by AlbericC** [comment]
Extra info:
After a Flake8 or syntactic check, the highlight bar appears sometimes, it seems random. I'll try to investigate further.

**Comment by tweekmonster** [comment]
This could be fixed in #4.  Could you confirm this after an update?

**Comment by jeetsukumaran** [comment]
You need to explicitly define the highlight color for the gui mode in your vimrc.

By default, only console vim colors are defined:

```
:highlight BracelessIndent
BracelessIndent xxx cterm=reverse ctermfg=3 ctermbg=0   
```

You need a line like the following in your `~/.vimrc` to support GUI mode vim colors:

```
  highlight BracelessIndent gui=none guibg=#353030
```

Or, specifying colors for both GUI and console:

```
 highlight BracelessIndent gui=none guibg=#353030 cterm=reverse ctermfg=3 ctermbg=0   
```

**Comment by tweekmonster** [comment]
I set the default to:

``` vim
highlight default BracelessIndent ctermfg=3 cterm=inverse guifg=#ffcc00 gui=inverse
```

**Comment by AlbericC** [comment]
I forgot to confirm, it worked perfectly. Sorry for the delay.
